In [1]:
import random
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
from tqdm import tqdm
import pandas as pd
token="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"

In [2]:

# Загружаем вашу дообученную модель (или базовую Llama-3.1)
model_name = "meta-llama/Llama-3.1-8B-Instruct"  # или путь к вашей LoRA
tokenizer = AutoTokenizer.from_pretrained(model_name, token =  token)
model = AutoModelForCausalLM.from_pretrained(model_name, torch_dtype=torch.bfloat16, device_map="auto", )
model.eval()

`torch_dtype` is deprecated! Use `dtype` instead!

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

Some parameters are on the meta device because they were offloaded to the cpu.

LlamaForCausalLM(
  (model): LlamaModel(
    (embed_tokens): Embedding(128256, 4096)
    (layers): ModuleList(
      (0-31): 32 x LlamaDecoderLayer(
        (self_attn): LlamaAttention(
          (q_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (k_proj): Linear(in_features=4096, out_features=1024, bias=False)
          (v_proj): Linear(in_features=4096, out_features=1024, bias=False)
          (o_proj): Linear(in_features=4096, out_features=4096, bias=False)
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear(in_features=4096, out_features=14336, bias=False)
          (up_proj): Linear(in_features=4096, out_features=14336, bias=False)
          (down_proj): Linear(in_features=14336, out_features=4096, bias=False)
          (act_fn): SiLUActivation()
        )
        (input_layernorm): LlamaRMSNorm((4096,), eps=1e-05)
        (post_attention_layernorm): LlamaRMSNorm((4096,), eps=1e-05)
      )
    )
    (norm): LlamaRMSNorm((4096,), eps=1e-05)
    (rotary_emb): LlamaRotaryEmbedding()
  )
  (lm_head): Linear(in_features=4096, out_features=128256, bias=False)
)

In [3]:

# Список тем для разнообразия
topics = [
    "погода", "спорт", "кулинария", "технологии", "путешествия",
    "кино", "политика", "здоровый образ жизни", "домашние животные",
    "искусство", "музыка", "образование", "наука (не генетика)", "история"
]

In [6]:

def generate_offtopic_question(topic: str) -> str:
    prompt = f"""<|begin_of_text|><|start_header_id|>system<|end_header_id|>
Вы — помощник, который генерирует разнообразные вопросы на русском языке. Сгенерируйте один вопрос на тему «{topic}». Вопрос должен быть простым, естественным и не связанным с генетикой, кариотипами или медицинской генетикой. Не давайте пояснений, только вопрос.<|eot_id|>
<|start_header_id|>user<|end_header_id|>
Сгенерируй вопрос на тему {topic}.<|eot_id|>
<|start_header_id|>assistant<|end_header_id|>
"""
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=50,
            temperature=0.7,
            do_sample=True,
            top_p=0.9,
            pad_token_id=tokenizer.eos_token_id
        )
    response = tokenizer.decode(outputs[0][inputs.input_ids.shape[1]:], skip_special_tokens=True)
    # Очищаем от лишних символов
    question = response.strip().split('\n')[0]
    return question

In [7]:
# Генерируем 100 вопросов
offtopic_questions = []
for i in tqdm(range(100)):
    topic = random.choice(topics)
    q = generate_offtopic_question(topic)
    offtopic_questions.append(q)
    print(f"{i+1}. {q}")

  1%|          | 1/100 [00:04<08:14,  5.00s/it]

1. В каком году вышел в прокат фильм «Парк Юрского периода»?

  2%|▏         | 2/100 [00:06<04:54,  3.01s/it]

2. Как происходит процесс спонтанного воспламенения?

  3%|▎         | 3/100 [00:07<03:33,  2.20s/it]

3. Как работает система GPS в автомобиле?

  4%|▍         | 4/100 [00:11<04:10,  2.61s/it]

4. Какой фильм 1994 года является продолжением фильма "Родина минус одна" (1992)?

  5%|▌         | 5/100 [00:13<04:11,  2.65s/it]

5. Какие преимущества имеют сотовые телефоны с функцией съемной батареи?

  6%|▌         | 6/100 [00:16<04:11,  2.67s/it]

6. Какой фильм с Джорджем Клуни получил две премии "Оскар"?

  7%|▋         | 7/100 [00:18<03:44,  2.41s/it]

7. Какой город в мире наиболее часто посещают туристы?

  8%|▊         | 8/100 [00:21<04:01,  2.63s/it]

8. Какой из полководцев древнего Рима наиболее известен своей победой над карфагенянами?

  9%|▉         | 9/100 [00:23<03:40,  2.43s/it]

9. Какое домашнее животное чаще всего является питомцем у детей?

 10%|█         | 10/100 [00:25<03:19,  2.22s/it]

10. Какой физический процесс приводит к образованию облаков?

 11%|█         | 11/100 [00:27<03:20,  2.26s/it]

11. Каковы основные принципы идеологии либерализма в политике?

 12%|█▏        | 12/100 [00:28<02:48,  1.91s/it]

12. Что такое закон сохранения энергии?

 13%|█▎        | 13/100 [00:29<02:28,  1.71s/it]

13. Когда обычно начинается весна в России?

 14%|█▍        | 14/100 [00:31<02:21,  1.64s/it]

14. Что такое классический соус для пиццы?

 15%|█▌        | 15/100 [00:32<02:15,  1.59s/it]

15. Как приготовить идеальный соус бешамель?

 16%|█▌        | 16/100 [00:34<02:14,  1.60s/it]

16. Какие предметы изучаются в средней школе?

 17%|█▋        | 17/100 [00:36<02:25,  1.75s/it]

17. В каком году первый раз проводился чемпионат мира по футболу?

 18%|█▊        | 18/100 [00:38<02:20,  1.71s/it]

18. Что нужно сделать, чтобы приготовить идеальный омлет?

 19%|█▉        | 19/100 [00:39<02:01,  1.50s/it]

19. Чем кормят кошек?

 20%|██        | 20/100 [00:41<02:11,  1.64s/it]

20. Сколько фильмов в серии "Звездные войны"?

 21%|██        | 21/100 [00:43<02:32,  1.93s/it]

21. Что является характерной особенностью произведений импрессионистов?

 22%|██▏       | 22/100 [00:46<02:54,  2.24s/it]

22. Какое из произведений Микеланджело является одной из его наиболее известных скульптур?

 23%|██▎       | 23/100 [00:49<03:03,  2.39s/it]

23. Какой первый фильм снял известный режиссер Стивен Спилберг?

 24%|██▍       | 24/100 [00:51<03:03,  2.41s/it]

24. Приносят ли занятия йогой пользу для сердечно-сосудистой системы?

 25%|██▌       | 25/100 [00:53<02:32,  2.03s/it]

25. Как приготовить идеальный омлет?

 26%|██▌       | 26/100 [00:54<02:26,  1.98s/it]

26. Кто придумал термин "тепловой остров"?

 27%|██▋       | 27/100 [00:56<02:16,  1.87s/it]

27. Когда закончилась Первая мировая война?

 28%|██▊       | 28/100 [00:58<02:22,  1.98s/it]

28. Вы ожидаете значительного похолодания в ближайшие выходные?

 29%|██▉       | 29/100 [00:59<01:59,  1.69s/it]

29. Что такое классическая музыка?

 30%|███       | 30/100 [01:03<02:35,  2.22s/it]

30. Какую роль сыграл Великий китайский поезд в формировании путей сообщения в Китае?

 31%|███       | 31/100 [01:05<02:23,  2.08s/it]

31. Как работает процесс диффузии в физике?

 32%|███▏      | 32/100 [01:07<02:36,  2.31s/it]

32. Кто является основным оппонентом действующего президента в предвыборной гонке?

 33%|███▎      | 33/100 [01:10<02:33,  2.28s/it]

33. Кто является основным композитором оперы «Кармен»?

 34%|███▍      | 34/100 [01:12<02:32,  2.30s/it]

34. Какой из футболистов забил самый первый гол в истории чемпионата мира?

 35%|███▌      | 35/100 [01:14<02:28,  2.28s/it]

35. Чего не следует делать, если у собаки начали течь зубы?

 36%|███▌      | 36/100 [01:17<02:43,  2.56s/it]

36. Какие преимущества принесет реализация единой европейской политики в сфере обороны?

 37%|███▋      | 37/100 [01:20<02:39,  2.54s/it]

37. Как часто необходимо посещать массажиста, чтобы поддерживать здоровье спины?

 38%|███▊      | 38/100 [01:23<02:50,  2.74s/it]

38. Как называется популярная песня Элтона Джона о любви к бельгийскому принцу?

 39%|███▉      | 39/100 [01:25<02:26,  2.40s/it]

39. Как работает принцип парения воды в вакууме?

 40%|████      | 40/100 [01:27<02:23,  2.39s/it]

40. Выгуляете ли вы своего собаку больше, чем раз в неделю?

 41%|████      | 41/100 [01:30<02:24,  2.45s/it]

41. В каком году умер легендарный британский певец Элтон Джон?

 42%|████▏     | 42/100 [01:32<02:12,  2.28s/it]

42. Что лучше, кошки или собаки как домашние животные?

 43%|████▎     | 43/100 [01:34<02:09,  2.27s/it]

43. Какой из вариантов соединения интернета наиболее часто используется в домашних условиях?

 44%|████▍     | 44/100 [01:37<02:22,  2.55s/it]

44. Какой фильм режиссера Квентина Тарантино выиграл несколько премий "Оскар"?

 45%|████▌     | 45/100 [01:40<02:35,  2.82s/it]

45. На каком расстоянии должны находиться друг от друга старт и финиш на дистанции 400 метров?

 46%|████▌     | 46/100 [01:43<02:25,  2.69s/it]

46. Какой спорт является наиболее популярен на Олимпийских играх?

 47%|████▋     | 47/100 [01:45<02:07,  2.40s/it]

47. Каковы основные компоненты атмосферы Земли?

 48%|████▊     | 48/100 [01:46<01:54,  2.20s/it]

48. Что такое черная дыра в астрономии?

 49%|████▉     | 49/100 [01:49<02:06,  2.47s/it]

49. Чем отличается технология 3D-печати от традиционной технологии изготовления изделий?

 50%|█████     | 50/100 [01:51<01:48,  2.18s/it]

50. Какая погода ожидается на выходных?

 51%|█████     | 51/100 [01:52<01:31,  1.86s/it]

51. Вы когда-нибудь были в Париже?

 52%|█████▏    | 52/100 [01:53<01:13,  1.53s/it]

52. Что такое джаз?

 53%|█████▎    | 53/100 [01:56<01:30,  1.93s/it]

53. Какой фильм снят по мотивам произведений Уильяма Шекспира?

 54%|█████▍    | 54/100 [01:57<01:17,  1.68s/it]

54. Как приготовить идеальный омлет?

 55%|█████▌    | 55/100 [01:59<01:28,  1.96s/it]

55. Кто является основным автором симфонии «Крейцерова соната»?

 56%|█████▌    | 56/100 [02:03<01:44,  2.37s/it]

56. Придумайте систему быстрого и простого способа записи и ведения дневника физической активности.

 57%|█████▋    | 57/100 [02:03<01:21,  1.89s/it]

57. Что такое блюз?

 58%|█████▊    | 58/100 [02:07<01:34,  2.25s/it]

58. Вы считаете, что физические упражнения являются важнейшим аспектом здорового образа жизни?

 59%|█████▉    | 59/100 [02:09<01:32,  2.24s/it]

59. Выгуливаете ли вы своих собак чаще зимой или летом?

 60%|██████    | 60/100 [02:10<01:23,  2.09s/it]

60. Какой вид спорта является национальным в Японии?

 61%|██████    | 61/100 [02:13<01:23,  2.13s/it]

61. Приготовьтесь к пробежке утром: полезно или вредно?

 62%|██████▏   | 62/100 [02:15<01:23,  2.20s/it]

62. Какие предметы часто изучают на первом курсе медицинского института?

 63%|██████▎   | 63/100 [02:17<01:20,  2.17s/it]

63. Как часто следует делать перерывы при выполнении физических упражнений?

 64%|██████▍   | 64/100 [02:20<01:24,  2.34s/it]

64. Какой фильм ознаменовал начало франшизы "Звездные войны"?

 65%|██████▌   | 65/100 [02:24<01:45,  3.01s/it]

65. Какой из футболистов, победивших в Лиге чемпионов, не выигрывал ни одного титула в своей национальной сборной?

 66%|██████▌   | 66/100 [02:26<01:24,  2.48s/it]

66. Как часто нужно купать собаку?

 67%|██████▋   | 67/100 [02:27<01:12,  2.18s/it]

67. Каковы основные принципы кубизма?

 68%|██████▊   | 68/100 [02:28<00:59,  1.86s/it]

68. Что такое сверхпроводимость?

 69%|██████▉   | 69/100 [02:31<01:04,  2.08s/it]

69. Чего вы обычно берете с собой на путешествие в незнакомый город?

 70%|███████   | 70/100 [02:32<00:53,  1.79s/it]

70. Как приготовить идеальный омлет?

 71%|███████   | 71/100 [02:36<01:06,  2.30s/it]

71. Кто является автором знаменитой музыкальной композиции "Ночь на Лысой горе"?

 72%|███████▏  | 72/100 [02:39<01:15,  2.68s/it]

72. Кто является победителем в личном многоборье на Олимпийских играх в Токио-2020?

 73%|███████▎  | 73/100 [02:42<01:10,  2.62s/it]

73. Что является основным преимуществом принятия федерализма в стране?

 74%|███████▍  | 74/100 [02:43<01:02,  2.40s/it]

74. Как приготовить идеально пропеченное тесто для пиццы?

 75%|███████▌  | 75/100 [02:45<00:50,  2.01s/it]

75. Что такое принцип Архимеда?

 76%|███████▌  | 76/100 [02:49<01:03,  2.63s/it]

76. Какое из древних городов, расположенных на побережье Средиземного моря, является самым посещаемым туристами?

 77%|███████▋  | 77/100 [02:50<00:52,  2.29s/it]

77. Какой самый популярный вид спорта в мире?

 78%|███████▊  | 78/100 [02:52<00:48,  2.20s/it]

78. Вы когда-нибудь слышали о концепции "интернета вещей"?

 79%|███████▉  | 79/100 [02:54<00:46,  2.21s/it]

79. Как формируется звук во время взрыва взрывчатых веществ?

 80%|████████  | 80/100 [02:58<00:50,  2.51s/it]

80. Как важно регулярно заниматься физическими упражнениями для поддержания хорошего самочувствия?

 81%|████████  | 81/100 [02:59<00:41,  2.17s/it]

81. Как работает технология распознавания лиц?

 82%|████████▏ | 82/100 [03:02<00:45,  2.55s/it]

82. Какое событие 9 мая 1945 года ознаменовало конец Второй мировой войны?

 83%|████████▎ | 83/100 [03:05<00:44,  2.61s/it]

83. В каком году вышел в свет фильм «Парк Юрского периода»?

 84%|████████▍ | 84/100 [03:06<00:34,  2.16s/it]

84. Как приготовить идеальный омлет?

 85%|████████▌ | 85/100 [03:08<00:32,  2.15s/it]

85. Как работают молниеотводы во время сильного ливня?

 86%|████████▌ | 86/100 [03:10<00:29,  2.13s/it]

86. Каковы основные направления деятельности в области высшего образования в России?

 87%|████████▋ | 87/100 [03:13<00:30,  2.38s/it]

87. Почему в футболе так важно сначала начать игру с подачей мяча?

 88%|████████▊ | 88/100 [03:16<00:27,  2.30s/it]

88. Кто из художников создал картину "Мона Лиза"?

 89%|████████▉ | 89/100 [03:17<00:21,  1.98s/it]

89. Что такое барокко в музыке?

 90%|█████████ | 90/100 [03:18<00:19,  1.91s/it]

90. Вы когда-нибудь были на дистанционном курсе?

 91%|█████████ | 91/100 [03:21<00:18,  2.04s/it]

91. В каких месяцах года обычно наблюдается наиболее низкая температура воздуха в Москве?

 92%|█████████▏| 92/100 [03:23<00:16,  2.10s/it]

92. Какой месяц в году обычно самая холодная погода в Москве?

 93%|█████████▎| 93/100 [03:26<00:15,  2.21s/it]

93. Какие преимущества есть у использования 3D-печати в производстве?

 94%|█████████▍| 94/100 [03:27<00:11,  1.88s/it]

94. Вы когда-нибудь были в Париже?

 95%|█████████▌| 95/100 [03:29<00:09,  1.99s/it]

95. Что лучше: посещать фитнес-клуб утром или вечером?

 96%|█████████▌| 96/100 [03:32<00:08,  2.24s/it]

96. Можно ли вылечить зависимость от кофеиновой зависимости без медицинской помощи?

 97%|█████████▋| 97/100 [03:34<00:06,  2.13s/it]

97. Какой тип учебных заведений наиболее распространен в России?

 98%|█████████▊| 98/100 [03:35<00:03,  1.87s/it]

98. Как часто следует купать собаку?

 99%|█████████▉| 99/100 [03:36<00:01,  1.68s/it]

99. Как работает процесс печати 3D?

100%|██████████| 100/100 [03:39<00:00,  2.20s/it]

100. Какое из произведений Джорджа Оруэлла является его первым большим романом?

In [17]:
offtopic_questions_df = pd.DataFrame({
    "Вопрос": offtopic_questions,
    "Класс": 0
})
offtopic_questions_df.to_excel("offtopic.xlsx")
offtopic_questions_df

                                               Вопрос  Класс
0   В каком году вышел в прокат фильм «Парк Юрског...      0
1   Как происходит процесс спонтанного воспламенения?      0
2              Как работает система GPS в автомобиле?      0
3   Какой фильм 1994 года является продолжением фи...      0
4   Какие преимущества имеют сотовые телефоны с фу...      0
..                                                ...    ...
95  Можно ли вылечить зависимость от кофеиновой за...      0
96  Какой тип учебных заведений наиболее распростр...      0
97                   Как часто следует купать собаку?      0
98                    Как работает процесс печати 3D?      0
99  Какое из произведений Джорджа Оруэлла является...      0

[100 rows x 2 columns]

In [18]:
# Генерируем 100 вопросов
offtopic_questions_val = []
for i in tqdm(range(100)):
    topic = random.choice(topics)
    q = generate_offtopic_question(topic)
    offtopic_questions_val.append(q)
    print(f"{i+1}. {q}")

  1%|          | 1/100 [00:03<05:46,  3.50s/it]

1. Существует ли технология, которая позволяет переводить человеческую речь в письменный текст в режиме реального времени?

  2%|▏         | 2/100 [00:05<04:08,  2.54s/it]

2. Что такое принцип действия атомной электростанции?

  3%|▎         | 3/100 [00:08<04:25,  2.73s/it]

3. Погодные условия в вашем городе в эту пятницу будут лучше, чем на прошлой неделе?

  4%|▍         | 4/100 [00:10<03:53,  2.44s/it]

4. Какой предмет в школе изучается обычно на втором классе?

  5%|▌         | 5/100 [00:12<03:40,  2.32s/it]

5. Что такое характеристика музыкального произведения?

  6%|▌         | 6/100 [00:14<03:43,  2.37s/it]

6. Кто сыграл роль главного героя в фильме "Титаник"?

  7%|▋         | 7/100 [00:16<03:14,  2.09s/it]

7. Пойдет ли в пятницу дождь?

  8%|▊         | 8/100 [00:19<03:41,  2.41s/it]

8. Какой из фильмов Джеймса Кэмерона является продолжением фильма "Терминатор"?

  9%|▉         | 9/100 [00:21<03:40,  2.43s/it]

9. В каком году основан знаменитый рок-фестиваль Woodstock?

 10%|█         | 10/100 [00:23<03:22,  2.25s/it]

10. Кто написал знаменитую песню "Imagine"?

 11%|█         | 11/100 [00:24<02:46,  1.87s/it]

11. Что такое классическая музыка?

 12%|█▏        | 12/100 [00:25<02:21,  1.60s/it]

12. Как приготовить идеальный торт?

 13%|█▎        | 13/100 [00:28<02:42,  1.87s/it]

13. Что является основной целью парламентских выборов в демократических странах?

 14%|█▍        | 14/100 [00:31<03:15,  2.28s/it]

14. Какой из композиторов написал известную симфонию "Кольца Нибелунга"?

 15%|█▌        | 15/100 [00:34<03:31,  2.49s/it]

15. Каковы основные различия между идеями политического либерализма и консерватизма?

 16%|█▌        | 16/100 [00:36<03:09,  2.26s/it]

16. Как часто нужно принимать холодный душ для поддержания здоровья?

 17%|█▋        | 17/100 [00:37<02:45,  1.99s/it]

17. Когда в Москве обычно начинается весна?

 18%|█▊        | 18/100 [00:39<02:43,  1.99s/it]

18. Что является главной темой фильма «Матрица»?

 19%|█▉        | 19/100 [00:43<03:26,  2.55s/it]

19. Какой из изотопов углерода используется в качестве временной метки в радиоуглеродном методе датирования?

 20%|██        | 20/100 [00:46<03:28,  2.60s/it]

20. Как работает технология искусственного интеллекта в современных компьютерных программах?

 21%|██        | 21/100 [00:47<02:50,  2.16s/it]

21. Как приготовить идеальную омлет?

 22%|██▏       | 22/100 [00:49<02:58,  2.29s/it]

22. Кто обычно ухаживает за домашним питомцем в отсутствие его владельцев?

 23%|██▎       | 23/100 [00:51<02:52,  2.24s/it]

23. Какой художник написал картину «Мона Лиза»?

 24%|██▍       | 24/100 [00:54<02:46,  2.20s/it]

24. Каковы основные принципы монументальной скульптуры?

 25%|██▌       | 25/100 [00:56<02:48,  2.25s/it]

25. Когда был основан первый олимпийский турнир по футболу?

 26%|██▌       | 26/100 [01:00<03:18,  2.69s/it]

26. Чем отличается работа электромагнитного импульсного преобразователя от работы электродвигателя?

 27%|██▋       | 27/100 [01:01<02:49,  2.33s/it]

27. В какой месяц в России начинается весна?

 28%|██▊       | 28/100 [01:04<02:50,  2.37s/it]

28. Зимние месяцы в вашем городе обычно холодные и снежные?

 29%|██▉       | 29/100 [01:05<02:32,  2.14s/it]

29. Вы когда-нибудь были на острова Гавайи?

 30%|███       | 30/100 [01:07<02:18,  1.98s/it]

30. Выгуляете ли вы собаку каждый день?

 31%|███       | 31/100 [01:09<02:19,  2.02s/it]

31. Какие животные являются наиболее популярными домашними питомцами в мире?

 32%|███▏      | 32/100 [01:10<02:04,  1.83s/it]

32. Как работает принцип работы солнечной батареи?

 33%|███▎      | 33/100 [01:13<02:27,  2.21s/it]

33. Какие преимущества дает использование технологии искусственного интеллекта в сфере бизнеса?

 34%|███▍      | 34/100 [01:15<02:16,  2.06s/it]

34. Когда лучше начинать заниматься йогой?

 35%|███▌      | 35/100 [01:17<02:12,  2.04s/it]

35. Вы когда-нибудь ходили на концерт своей любимой группы?

 36%|███▌      | 36/100 [01:19<02:09,  2.02s/it]

36. Какой вид спорта считается одним из самых физически требовательных?

 37%|███▋      | 37/100 [01:21<02:01,  1.93s/it]

37. Кто является основным автором песни «Imagine»?

 38%|███▊      | 38/100 [01:23<02:07,  2.06s/it]

38. Какой из вариантов интернет-провайдеров выбрать для домашнего использования?

 39%|███▉      | 39/100 [01:25<02:08,  2.11s/it]

39. Какое самое дальнее известное на данный момент звездообразование?

 40%|████      | 40/100 [01:28<02:21,  2.37s/it]

40. Кто сыграл роль Джеймса Бонда в фильме «Золотой глаз»?

 41%|████      | 41/100 [01:32<02:41,  2.73s/it]

41. Кто является рекордсменом по количеству золотых медалей на летних Олимпийских играх?

 42%|████▏     | 42/100 [01:34<02:31,  2.62s/it]

42. Какой самый первый спортивный марафон был проведен в Афинах?

 43%|████▎     | 43/100 [01:36<02:05,  2.21s/it]

43. Когда обычно начинается осень в России?

 44%|████▍     | 44/100 [01:38<02:14,  2.40s/it]

44. Представители каких видов спорта не могут принимать участие в Олимпийских играх?

 45%|████▌     | 45/100 [01:40<02:01,  2.20s/it]

45. Какой исторический деятель основал государство СССР?

 46%|████▌     | 46/100 [01:43<02:07,  2.36s/it]

46. Кто является победителем первых летних Олимпийских игр 1896 года?

 47%|████▋     | 47/100 [01:45<01:58,  2.25s/it]

47. Когда началось использование письменности в Древнем Китае?

 48%|████▊     | 48/100 [01:47<01:54,  2.20s/it]

48. Как часто вы посещаете парк или лес для прогулок?

 49%|████▉     | 49/100 [01:49<01:56,  2.29s/it]

49. Какой вид образования дает право на получение диплома о высшем образовании?

 50%|█████     | 50/100 [01:52<01:57,  2.34s/it]

50. Каковы основные причины, по которым политические партии формируют коалиции?

 51%|█████     | 51/100 [01:53<01:42,  2.09s/it]

51. Каковы основные цели среднего образования?

 52%|█████▏    | 52/100 [01:58<02:17,  2.87s/it]

52. В каком году на летних Олимпийских играх в Афинах в греко-римской борьбе стал чемпионом мира Алексей Мишин?

 53%|█████▎    | 53/100 [02:00<02:02,  2.60s/it]

53. Какой фильм снял Стивен Спилберг?

 54%|█████▍    | 54/100 [02:03<02:01,  2.64s/it]

54. В каких фильмах снималась актриса Джулия Робертс?

 55%|█████▌    | 55/100 [02:06<02:04,  2.77s/it]

55. Каковы основные жанры музыки в классическом музыкальном репертуаре?

 56%|█████▌    | 56/100 [02:12<02:47,  3.80s/it]

56. Мировая кинопремия «Оскар» присуждается за достижения в области кинематографа. Правда ли, что первая церемония награждения «Оскаром» состоялась в 192

 57%|█████▋    | 57/100 [02:14<02:21,  3.29s/it]

57. Кто является лидером оппозиции в парламенте России?

 58%|█████▊    | 58/100 [02:18<02:20,  3.34s/it]

58. Каковы основные отличия между спутниками естественного происхождения и тех, которые созданы человеком?

 59%|█████▉    | 59/100 [02:20<02:06,  3.08s/it]

59. Что такое принцип «долгожительство» в квантовой механике?

 60%|██████    | 60/100 [02:22<01:52,  2.82s/it]

60. Какой вид спорта является национальным видом спорта в Японии?

 61%|██████    | 61/100 [02:25<01:47,  2.76s/it]

61. Как работает принцип работы ядерной реакции в атомной электростанции?

 62%|██████▏   | 62/100 [02:28<01:47,  2.82s/it]

62. На каком стадионе проходит финальный матч Чемпионата мира по футболу?

 63%|██████▎   | 63/100 [02:31<01:48,  2.93s/it]

63. Какое из произведений Микеланджело является его наиболее известным скульптурным произведением?

 64%|██████▍   | 64/100 [02:33<01:38,  2.73s/it]

64. Вы когда-нибудь были в стране, которую вы всегда хотели посетить?

 65%|██████▌   | 65/100 [02:37<01:49,  3.14s/it]

65. Чем отличаются бег на длинные дистанции и бег на короткие дистанции по характеристикам?

 66%|██████▌   | 66/100 [02:40<01:44,  3.09s/it]

66. Кто сыграл роль Дэрэка в сериале «Доктор Кто»?

 67%|██████▋   | 67/100 [02:44<01:41,  3.09s/it]

67. Какое из произведений Леонардо да Винчи является одной из его самых известных картин?

 68%|██████▊   | 68/100 [02:46<01:28,  2.76s/it]

68. Какие основные преимущества использования облачного хранения данных?

 69%|██████▉   | 69/100 [02:47<01:17,  2.49s/it]

69. Когда лучше всего ехать в горы на лыжи?

 70%|███████   | 70/100 [02:50<01:16,  2.56s/it]

70. Кто является основным тренером сборной России по футболу на Евро-2020?

 71%|███████   | 71/100 [02:53<01:14,  2.57s/it]

71. Кто сыграл главную роль в фильме "Властелин колец"?

 72%|███████▏  | 72/100 [02:56<01:15,  2.69s/it]

72. Какие типы материалов лучше всего подходят для использования в качестве топлива для ядерных реакторов?

 73%|███████▎  | 73/100 [02:59<01:13,  2.74s/it]

73. Что является основным преимуществом прямых выборов президента в демократической системе?

 74%|███████▍  | 74/100 [03:02<01:14,  2.85s/it]

74. Когда вы путешествуете по незнакомой стране, что обычно делаете в первую очередь?

 75%|███████▌  | 75/100 [03:04<01:09,  2.77s/it]

75. Кто является создателем знаменитой картины «Мона Лиза»?

 76%|███████▌  | 76/100 [03:07<01:03,  2.64s/it]

76. Могут ли домашние животные приобрести вредную привычку?

 77%|███████▋  | 77/100 [03:08<00:50,  2.18s/it]

77. Как приготовить идеальную омлет?

 78%|███████▊  | 78/100 [03:09<00:45,  2.05s/it]

78. Когда началась Вторая мировая война?

 79%|███████▉  | 79/100 [03:11<00:41,  1.95s/it]

79. Что такое процесс создания искусственного интеллекта?

 80%|████████  | 80/100 [03:13<00:40,  2.04s/it]

80. Почему кошки часто начинают мычать во время спанья?

 81%|████████  | 81/100 [03:15<00:38,  2.02s/it]

81. Какое из произведений Микеланджело является завершенным?

 82%|████████▏ | 82/100 [03:18<00:40,  2.27s/it]

82. Придумываете ли вы себе время для ежедневных зарядок и йоги?

 83%|████████▎ | 83/100 [03:19<00:30,  1.81s/it]

83. Что такое джаз?

 84%|████████▍ | 84/100 [03:21<00:29,  1.87s/it]

84. Как часто следует принимать перерывы во время физических упражнений?

 85%|████████▌ | 85/100 [03:22<00:25,  1.68s/it]

85. Как часто нужно кормить собаку?

 86%|████████▌ | 86/100 [03:26<00:30,  2.21s/it]

86. Какие преимущества у использования электронных документов вместо бумажных в офисе?

 87%|████████▋ | 87/100 [03:27<00:27,  2.11s/it]

87. Кто был автором картины "Мона Лиза"?

 88%|████████▊ | 88/100 [03:29<00:24,  2.03s/it]

88. Какое самое популярное музыкальное направление в мире?

 89%|████████▉ | 89/100 [03:31<00:21,  1.91s/it]

89. Какое образование необходимо для работы в сфере образования?

 90%|█████████ | 90/100 [03:33<00:20,  2.04s/it]

90. Как часто нужно пить воды в день, чтобы поддерживать организм в нормальном состоянии?

 91%|█████████ | 91/100 [03:35<00:16,  1.80s/it]

91. Когда лучше посещать Тибет?

 92%|█████████▏| 92/100 [03:36<00:14,  1.82s/it]

92. Какие предметы обычно изучаются в 9-м классе?

 93%|█████████▎| 93/100 [03:39<00:14,  2.12s/it]

93. Какой фильм 1994 года стал первым в серии фильмов про Хана Соло?

 94%|█████████▍| 94/100 [03:43<00:15,  2.60s/it]

94. Кто является рекордсменом по количеству побед на олимпийских играх по фигурному катанию?

 95%|█████████▌| 95/100 [03:45<00:11,  2.38s/it]

95. Как работает система распознавания лиц на смартфонах?

 96%|█████████▌| 96/100 [03:47<00:08,  2.19s/it]

96. Когда началась Вторая мировая война?

 97%|█████████▋| 97/100 [03:50<00:07,  2.42s/it]

97. Кто является лидером по количеству выигранных титулов в теннисе?

 98%|█████████▊| 98/100 [03:52<00:04,  2.37s/it]

98. В каком месяце обычно бывает самое холодное время года в Москве?

 99%|█████████▉| 99/100 [03:54<00:02,  2.33s/it]

99. Каковы самые популярные туристические места на острове Крит?

100%|██████████| 100/100 [03:55<00:00,  2.36s/it]

100. Как работает принцип действия радиоактивных часов?

In [19]:
offtopic_questions_df_val = pd.DataFrame({
    "Вопрос": offtopic_questions_val,
    "Класс": 0
})
offtopic_questions_df_val.to_excel("offtopic_val.xlsx")
offtopic_questions_df_val

                                               Вопрос  Класс
0   Существует ли технология, которая позволяет пе...      0
1   Что такое принцип действия атомной электростан...      0
2   Погодные условия в вашем городе в эту пятницу ...      0
3   Какой предмет в школе изучается обычно на втор...      0
4   Что такое характеристика музыкального произвед...      0
..                                                ...    ...
95               Когда началась Вторая мировая война?      0
96  Кто является лидером по количеству выигранных ...      0
97  В каком месяце обычно бывает самое холодное вр...      0
98  Каковы самые популярные туристические места на...      0
99  Как работает принцип действия радиоактивных ча...      0

[100 rows x 2 columns]