In [1]:
from transformers import AutoModelForCausalLM, AutoTokenizer, TextStreamer
import torch
from peft import PeftModel
device = "cuda" if torch.cuda.is_available() else "cpu"
print("device:", device)
from gpu_monitor import *
model_name = "LORA_THE_BEST"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name, device_map="auto")
import time
import pandas as pd
from tqdm import tqdm

device: cuda

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

In [2]:
prompt = "Мой кариотип 46,XY,der(21;21)(q10;q10),+21. Что это значит?"
inputs = tokenizer([prompt], return_tensors="pt").to(device)   # <-- вот так
model.past_key_values = None
streamer = TextStreamer(tokenizer, skip_prompt=True)
start_time = time.perf_counter()
output_ids = model.generate(
    **inputs,
    #streamer=streamer,
    max_new_tokens=1600,
    early_stopping=True,
    use_cache=False, 
    #no_repeat_ngram_size=2,
    #eos_token_id=tokenizer.eos_token_id,
)
answer = tokenizer.decode(output_ids[0], skip_special_tokens=True)
end_time = time.perf_counter()

print("Ответ модели:")
print(answer)
print(f"\nВремя выполнения: {end_time - start_time:.3f} секунд")

The following generation flags are not valid and may be ignored: ['early_stopping']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Ответ модели:
Мой кариотип 46,XY,der(21;21)(q10;q10),+21. Что это значит? Что изменения произошли в клетках организма? Что это значит для здоровья человека? Что это значит для риска рождения ребёнка с синдромом Дауна? Что это значит для семейного консультирования? Что это значит для планирования будущих беременностей? Что это значит для наблюдения пациента? Что это значит для оценки прогноза? Что это значит для поддержки родителей? Что это значит для образования фонограммы риска? Что это значит для интерпретации генетического консультирования? Что это значит для обследования родителей? Что это значит для оценки наследования? Что это значит для генетического консультирования родителей? Что это значит для планирования беременности с учетом инвазивной диагностики? Что это значит для наблюдения материале? Что это значит для оценки риска повторного рождения ребёнка с синдромом Дауна? Что это значит для поддержки материале? Что это значит для образования фонограммы риска повторного рождения? Что это значит для интерпретации генетического консультирования повторного рождения? Что это значит для обследования отца? Что это значит для оценки наследования отца? Что это значит для генетического консультирования отца? Что это значит для планирования беременности с ультиматерным кариотипом? Что это значит для наблюдения отца? Что это значит для оценки риска повторного рождения ребёнка с синдромом Дауна? Что это значит для поддержки отца? Что это значит для образования фонограммы риска повторного рождения? Что это значит для интерпретации генетического консультирования повторного рождения? Что это значит для обследования материале и отца? Что это значит для оценки наследования материале и отца? Что это значит для генетического консультирования материале и отца? Что это значит для планирования беременности с ультиматерным кариотипом и молекулярным уточнением? Что это значит для наблюдения материале и отца? Что это значит для оценки риска повторного рождения ребёнка с синдромом Дауна? Что это значит для поддержки материале и отца? Что это значит для образования фонограммы риска повторного рождения? Что это значит для интерпретации генетического консультирования повторного рождения? Что это значит для обследования родителей, материале и отца? Что это значит для оценки наследования родителей, материале и отца? Что это значит для генетического консультирования родителей, материале и отца? Что это значит для планирования беременности с ультиматерным кариотипом, молекулярным уточнением и пренатальной диагностикой? Что это значит для наблюдения родителей, материале и отца? Что это значит для оценки риска повторного рождения ребёнка с синдромом Дауна? Что это значит для поддержки родителей, материале и отца? Что это значит для образования фонограммы риска повторного рождения? Что это значит для интерпретации генетического консультирования повторного рождения? Что это значит для обследования родителей, материале и отца с молекулярным уточнением? Что это значит для оценки наследования родителей, материале и отца с молекулярным уточнением? Что это значит для генетического консультирования родителей, материале и отца с молекулярным уточнением? Что это значит для планирования беременности с ультиматерным кариотипом, молекулярным уточнением и пренатальной диагностикой? Что это значит для наблюдения родителей, материале и отца? Что это значит для оценки риска повторного рождения ребёнка с синдромом Дауна? Что это значит для поддержки родителей, материале и отца? Что это значит для образования фонограммы риска повторного рождения? Что это значит для интерпретации генетического консультирования повторного рождения? Что это значит для обследования родителей, материале и отца с молекулярным уточнением и пренатальной диагностикой? Что это значит для оценки наследования родителей, материале и отца с молекулярным уточнением и пренатальной диагностикой? Что это значит для генетического консультирования родителей, материале и отца с молекулярным уточнением и пренатальной диагностикой? Что это значит для планирования беременности с ультиматерным кариотипом, молекулярным уточнением, пренатальной диагностикой и генетическим консультированием? Что это значит для наблюдения родителей, материале и отца? Что это значит для оценки риска повторного рождения ребёнка с синдромом Дауна? Что это значит для поддержки родителей, материале и отца? Что это значит для образования фонограммы риска повторного рождения? Что это значит для интерпретации генетического консультирования повторного рождения? Что это значит для обследования родителей, материале и отца с молекулярным уточнением, пренатальной диагностикой и генетическим консультированием? Что это значит для оценки наследления родителей, материале и отца с молекулярным уточнением, пренатальной диагностикой и генетическим консультированием? Что это значит для генетического консультирования родителей, материале и отца с молекулярным уточнением, пренатальной диагностикой и генетическим консультированием? Что это значит для планирования беременности с ультиматерным кариотипом, молекулярным уточнением, пренатальной диагностикой, генетическим консультированием и медико-генетическим наблюдением? Что это значит для наблюдения родителей, материале и отца? Что это значит для оценки риска повторного рождения ребёнка с синдромом Дауна? Что это значит для поддержки родителей, материале и отца? Что это значит для образования фонограммы риска повторного рождения? Что это значит для интерпретации генетического консультирования повторного рождения? Что это значит для обследования родителей, материале и отца с молекулярным уточнением, пренатальной диагностикой, генетическим консультированием и медико-генетическим наблюдением? Что это значит для оценки наследования родителей, материале и отца с молекулярным уточнением, пренатальной диагностикой, генетическим консультированием и медико-генетическим наблюдением? Что это значит для генетического консультирования родителей, материале и отца с молекулярным уточнением, пренатальной диагностикой, генетическим консультированием и медико-генетическим наблюдением? Что это значит для планирования беременности с ультиматерным кариотипом, молекулярным уточнением, пренатальной диагностикой, генетическим консультированием, медико-

Время выполнения: 126.528 секунд

In [3]:


def transformers_ai_answer(prompt):
    monitor = GPUMonitor(device_id=0)
    monitor.start()
    
    start_time = time.perf_counter()
    
    inputs = tokenizer([prompt], return_tensors="pt").to(device)
    model.past_key_values = None
    streamer = TextStreamer(tokenizer, skip_prompt=True)
    start_time = time.perf_counter()
    output_ids = model.generate(
        **inputs,
        max_new_tokens=1600,
        early_stopping=True,
        use_cache=False, 

    )
    answer = tokenizer.decode(output_ids[0], skip_special_tokens=True)
    end_time = time.perf_counter()

    
    avg_power, max_power, avg_util = monitor.stop()
    response_time = end_time - start_time
    input_len = inputs['input_ids'].shape[1]
    output_len = output_ids.shape[1]
    completion_tokens = output_len - input_len
    tokens_per_second = completion_tokens / response_time if response_time > 0 else 0
    tokens_per_sec_per_watt = tokens_per_second / avg_power if avg_power > 0 else 0
    
    return {
        'answer': answer,
        'response_time': response_time,
        'completion_tokens': completion_tokens,
        'tokens_per_second': tokens_per_second,
        'avg_power_watts': avg_power,
        'max_power_watts': max_power,
        'avg_gpu_util': avg_util,
        'tokens_per_sec_per_watt': tokens_per_sec_per_watt
    }

In [4]:
transformers_ai_answer("Мой кариотип 47,XX,+i(12)(p10). Что это значит?")

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

{'answer': 'Мой кариотип 47,XX,+i(12)(p10). Что это значит? Что ещё i(12p)?\nКариотип: 47,XX,+i(12)(p10)\nТип: изохромосома короткого плеча 12 (i(12p))\nГруппа: синдром Паллаистера–Киллиана\n\n1. Суть\nДополнительная изохромосома 12p → тетрасомия 12p (обычно мозаичная).\n\n2. Клиника\n• выраженная задержка развития\n• гипотония\n• характерные лицевые особенности\n• врождённые пороки\n\n3. Особенности\nЧасто не выявляется в крови, требуется исследование фибробластов.\n\n4. Заключение\ni(12p) ассоциирована с синдромом Паллаистера–Киллиана, тяжесть зависит от уровня мозаицизма.',
 'response_time': 4.6624695059999794,
 'completion_tokens': 205,
 'tokens_per_second': 43.96811598149697,
 'avg_power_watts': 469.1891914893617,
 'max_power_watts': 480.912,
 'avg_gpu_util': 94.23404255319149,
 'tokens_per_sec_per_watt': 0.09371084581451594}

In [5]:
df = pd.read_excel("Q_F_T.xlsx")
df

,Promts,References
0,"Мой кариотип 46,XX,t(9;13)(p11;q21). Что это з...",Тип перестройки: сбалансированная реципрокная ...
1,"Мой кариотип 46,XX,inv(17)(q32q33). Что это зн...","Кариотип: 46,XX,inv(17)(q32q33)\nТип хромосомн..."
2,"Мой кариотип 47,XX,+8[10]/46,XX[15]. Что это з...","Кариотип: 47,XX,+8[10]/46,XX[15]\nТип хромосом..."
3,"Мой кариотип 49,XXXXY. Что это значит?","Кариотип: 49,XXXXY\nТип хромосомной аномалии: ..."
4,"Мой кариотип 45,XY,der(22;22)(q10;q10). Что эт...","Кариотип: 45,XY,der(22;22)(q10;q10)\nТип перес..."
...,...,...
100,"Мой кариотип 45,XY,der(21;22)(q10;q10). Что эт...",Тип перестройки: сбалансированная Робертсоновс...
101,"Мой кариотип 47,XX,+i(12)(p10). Что это значит?","Кариотип: 47,XX,+i(12)(p10)\nТип: изохромосома..."
102,"Мой кариотип 46,XX,del(8)(p22). Что это значит?","Кариотип: 46,XX,del(8)(p22)\nТип хромосомной а..."
103,"Мой кариотип 46,XX,del(3)(q29q29). Что это зна...","Кариотип: 46,XX,del(3)(q29q29)\nТип хромосомно..."
104,"Мой кариотип 47,XX,+i(12)(p10). Что это значит?","Кариотип: 47,XX,+i(12)(p10)\nТип: изохромосома..."

In [8]:
results = []
for prompt in tqdm(df['Promts']):
     res = transformers_ai_answer(prompt)
     results.append(res)

  0%|          | 0/105 [00:00<?, ?it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  1%|          | 1/105 [01:04<1:51:00, 64.04s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  2%|▏         | 2/105 [03:09<2:52:10, 100.29s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  3%|▎         | 3/105 [03:34<1:51:54, 65.83s/it] Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  4%|▍         | 4/105 [05:39<2:29:59, 89.10s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  5%|▍         | 5/105 [07:45<2:50:43, 102.43s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  6%|▌         | 6/105 [09:51<3:02:10, 110.41s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  7%|▋         | 7/105 [11:56<3:08:13, 115.24s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  8%|▊         | 8/105 [14:02<3:11:46, 118.63s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  9%|▊         | 9/105 [14:04<2:11:46, 82.36s/it] Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 10%|▉         | 10/105 [14:34<1:44:45, 66.17s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 10%|█         | 11/105 [14:39<1:13:57, 47.20s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 11%|█▏        | 12/105 [14:47<54:46, 35.34s/it]  Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 12%|█▏        | 13/105 [16:53<1:36:20, 62.83s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 13%|█▎        | 14/105 [17:27<1:22:19, 54.28s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 14%|█▍        | 15/105 [19:33<1:53:46, 75.85s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 15%|█▌        | 16/105 [19:43<1:22:50, 55.85s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 16%|█▌        | 17/105 [20:06<1:07:41, 46.16s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 17%|█▋        | 18/105 [21:22<1:19:54, 55.11s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 18%|█▊        | 19/105 [21:46<1:05:28, 45.68s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 19%|█▉        | 20/105 [23:52<1:38:54, 69.82s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 20%|██        | 21/105 [25:58<2:01:20, 86.67s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 21%|██        | 22/105 [28:04<2:16:07, 98.40s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 22%|██▏       | 23/105 [29:09<2:00:55, 88.48s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 23%|██▎       | 24/105 [31:15<2:14:33, 99.68s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 24%|██▍       | 25/105 [33:20<2:23:13, 107.42s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 25%|██▍       | 26/105 [35:25<2:28:20, 112.66s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 26%|██▌       | 27/105 [37:31<2:31:34, 116.60s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 27%|██▋       | 28/105 [37:42<1:48:58, 84.92s/it] Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 28%|██▊       | 29/105 [38:40<1:37:23, 76.88s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 29%|██▊       | 30/105 [40:46<1:54:33, 91.64s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 30%|██▉       | 31/105 [41:47<1:41:42, 82.46s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 30%|███       | 32/105 [43:52<1:55:55, 95.28s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 31%|███▏      | 33/105 [43:59<1:22:31, 68.77s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 32%|███▏      | 34/105 [46:05<1:41:41, 85.93s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 33%|███▎      | 35/105 [47:31<1:40:09, 85.85s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 34%|███▍      | 36/105 [47:35<1:10:33, 61.36s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 35%|███▌      | 37/105 [49:41<1:31:32, 80.77s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 36%|███▌      | 38/105 [51:47<1:45:20, 94.33s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 37%|███▋      | 39/105 [51:54<1:14:45, 67.96s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 38%|███▊      | 40/105 [52:30<1:03:22, 58.50s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 39%|███▉      | 41/105 [53:35<1:04:19, 60.31s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 40%|████      | 42/105 [55:41<1:24:12, 80.19s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 41%|████      | 43/105 [57:48<1:37:09, 94.02s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 42%|████▏     | 44/105 [58:59<1:28:45, 87.31s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 43%|████▎     | 45/105 [59:11<1:04:43, 64.72s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 44%|████▍     | 46/105 [1:01:17<1:21:46, 83.16s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 45%|████▍     | 47/105 [1:03:23<1:32:50, 96.04s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 46%|████▌     | 48/105 [1:03:39<1:08:10, 71.76s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 47%|████▋     | 49/105 [1:05:10<1:12:31, 77.70s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 48%|████▊     | 50/105 [1:07:16<1:24:26, 92.12s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 49%|████▊     | 51/105 [1:08:12<1:13:16, 81.42s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 50%|████▉     | 52/105 [1:10:17<1:23:26, 94.46s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 50%|█████     | 53/105 [1:10:23<58:40, 67.71s/it]  Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 51%|█████▏    | 54/105 [1:10:29<42:01, 49.44s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 52%|█████▏    | 55/105 [1:12:35<1:00:23, 72.46s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 53%|█████▎    | 56/105 [1:14:42<1:12:23, 88.64s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 54%|█████▍    | 57/105 [1:15:23<59:23, 74.23s/it]  Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 55%|█████▌    | 58/105 [1:17:29<1:10:28, 89.97s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 56%|█████▌    | 59/105 [1:17:54<53:55, 70.33s/it]  Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 57%|█████▋    | 60/105 [1:18:18<42:29, 56.65s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 58%|█████▊    | 61/105 [1:18:42<34:15, 46.71s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 59%|█████▉    | 62/105 [1:19:00<27:24, 38.25s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 60%|██████    | 63/105 [1:20:01<31:31, 45.02s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 61%|██████    | 64/105 [1:22:07<47:15, 69.16s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 62%|██████▏   | 65/105 [1:24:13<57:35, 86.39s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 63%|██████▎   | 66/105 [1:26:20<1:04:01, 98.50s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 64%|██████▍   | 67/105 [1:28:27<1:07:42, 106.90s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 65%|██████▍   | 68/105 [1:30:33<1:09:30, 112.71s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 66%|██████▌   | 69/105 [1:30:38<48:18, 80.52s/it]   Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 67%|██████▋   | 70/105 [1:32:44<54:57, 94.22s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 68%|██████▊   | 71/105 [1:34:51<58:50, 103.84s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 69%|██████▊   | 72/105 [1:36:57<1:00:52, 110.69s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 70%|██████▉   | 73/105 [1:37:08<43:04, 80.75s/it]   Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 70%|███████   | 74/105 [1:39:15<48:49, 94.50s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 71%|███████▏  | 75/105 [1:41:21<52:02, 104.09s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 72%|███████▏  | 76/105 [1:43:28<53:34, 110.84s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 73%|███████▎  | 77/105 [1:45:34<53:54, 115.53s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 74%|███████▍  | 78/105 [1:45:45<37:52, 84.17s/it] Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 75%|███████▌  | 79/105 [1:47:52<41:56, 96.80s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 76%|███████▌  | 80/105 [1:49:58<44:01, 105.65s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 77%|███████▋  | 81/105 [1:51:26<40:05, 100.22s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 78%|███████▊  | 82/105 [1:51:32<27:38, 72.11s/it] Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 79%|███████▉  | 83/105 [1:53:38<32:23, 88.36s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 80%|████████  | 84/105 [1:55:47<35:11, 100.54s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 81%|████████  | 85/105 [1:57:54<36:05, 108.26s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 82%|████████▏ | 86/105 [2:00:00<36:02, 113.79s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 83%|████████▎ | 87/105 [2:02:07<35:16, 117.60s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 84%|████████▍ | 88/105 [2:02:42<26:20, 92.97s/it] Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 85%|████████▍ | 89/105 [2:02:50<18:00, 67.54s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 86%|████████▌ | 90/105 [2:03:24<14:20, 57.40s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 87%|████████▋ | 91/105 [2:03:57<11:41, 50.11s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 88%|████████▊ | 92/105 [2:06:02<15:44, 72.63s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 89%|████████▊ | 93/105 [2:06:12<10:45, 53.75s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 90%|████████▉ | 94/105 [2:06:36<08:11, 44.71s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 90%|█████████ | 95/105 [2:08:32<11:00, 66.03s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 91%|█████████▏| 96/105 [2:08:42<07:23, 49.28s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 92%|█████████▏| 97/105 [2:10:51<09:45, 73.16s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 93%|█████████▎| 98/105 [2:11:04<06:26, 55.27s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 94%|█████████▍| 99/105 [2:13:10<07:39, 76.54s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 95%|█████████▌| 100/105 [2:15:17<07:38, 91.61s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 96%|█████████▌| 101/105 [2:17:24<06:48, 102.14s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 97%|█████████▋| 102/105 [2:19:30<05:28, 109.38s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 98%|█████████▊| 103/105 [2:21:36<03:48, 114.39s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
 99%|█████████▉| 104/105 [2:21:44<01:22, 82.29s/it] Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
100%|██████████| 105/105 [2:21:48<00:00, 81.04s/it]

In [9]:
answers = [item['answer'] for item in results]
response_times = [item['response_time'] for item in results]
completion_tokens = [item['completion_tokens'] for item in results]
tokens_per_second = [item['tokens_per_second'] for item in results]
avg_power = [item['avg_power_watts'] for item in results]
max_power = [item['max_power_watts'] for item in results]
avg_gpu_util = [item['avg_gpu_util'] for item in results]
tps_per_watt = [item['tokens_per_sec_per_watt'] for item in results]

In [10]:
df["Answers"] = answers
df["Response times"] = response_times
df["Completion tokens"] = completion_tokens
df["Tokens per second"] = tokens_per_second
df["Avg Power (W)"] = avg_power
df["Max Power (W)"] = max_power
df["Avg GPU Util (%)"] = avg_gpu_util
df["Tokens/s per Watt"] = tps_per_watt

In [11]:
df.to_excel("TRANSFORMERS_TEST.xlsx", index = False)
df

,Promts,References,Answers,Response times,Completion tokens,Tokens per second,Avg Power (W),Max Power (W),Avg GPU Util (%),Tokens/s per Watt
0,"Мой кариотип 46,XX,t(9;13)(p11;q21). Что это з...",Тип перестройки: сбалансированная реципрокная ...,"Мой кариотип 46,XX,t(9;13)(p11;q21). Что это з...",63.952476,1096,17.137726,462.040781,480.725,96.757812,0.037091
1,"Мой кариотип 46,XX,inv(17)(q32q33). Что это зн...","Кариотип: 46,XX,inv(17)(q32q33)\nТип хромосомн...","Мой кариотип 46,XX,inv(17)(q32q33). Что это зн...",125.636507,1600,12.735152,469.658362,480.040,98.307325,0.027116
2,"Мой кариотип 47,XX,+8[10]/46,XX[15]. Что это з...","Кариотип: 47,XX,+8[10]/46,XX[15]\nТип хромосом...","Мой кариотип 47,XX,+8[10]/46,XX[15]. Что это з...",24.763738,610,24.632792,469.559060,481.335,96.661290,0.052459
3,"Мой кариотип 49,XXXXY. Что это значит?","Кариотип: 49,XXXXY\nТип хромосомной аномалии: ...","Мой кариотип 49,XXXXY. Что это значит? Что изм...",124.728043,1600,12.827909,469.779755,480.182,98.165998,0.027306
4,"Мой кариотип 45,XY,der(22;22)(q10;q10). Что эт...","Кариотип: 45,XY,der(22;22)(q10;q10)\nТип перес...","Мой кариотип 45,XY,der(22;22)(q10;q10). Что эт...",125.969802,1600,12.701457,469.815464,480.369,98.277778,0.027035
...,...,...,...,...,...,...,...,...,...,...
100,"Мой кариотип 45,XY,der(21;22)(q10;q10). Что эт...",Тип перестройки: сбалансированная Робертсоновс...,"Мой кариотип 45,XY,der(21;22)(q10;q10). Что эт...",126.655504,1600,12.632692,469.988679,476.595,98.305687,0.026879
101,"Мой кариотип 47,XX,+i(12)(p10). Что это значит?","Кариотип: 47,XX,+i(12)(p10)\nТип: изохромосома...","Мой кариотип 47,XX,+i(12)(p10). Что это значит...",126.187605,1600,12.679534,469.856376,479.451,98.318542,0.026986
102,"Мой кариотип 46,XX,del(8)(p22). Что это значит?","Кариотип: 46,XX,del(8)(p22)\nТип хромосомной а...","Мой кариотип 46,XX,del(8)(p22). Что это значит...",126.024630,1600,12.695931,469.766775,479.585,98.277778,0.027026
103,"Мой кариотип 46,XX,del(3)(q29q29). Что это зна...","Кариотип: 46,XX,del(3)(q29q29)\nТип хромосомно...","Мой кариотип 46,XX,del(3)(q29q29). Что это зна...",7.377847,280,37.951450,468.152189,479.577,94.540541,0.081066
104,"Мой кариотип 47,XX,+i(12)(p10). Что это значит?","Кариотип: 47,XX,+i(12)(p10)\nТип: изохромосома...","Мой кариотип 47,XX,+i(12)(p10). Что это значит...",4.696665,206,43.860907,468.634277,478.301,94.127660,0.093593